In [ ]:
#installing pandas
pip install pandas

Collecting pandas
  Downloading pandas-3.1.0-cp312-cp312-win_amd64.whl.metadata (18 kB)
Collecting numpy>=2.0.2 (from pandas)
  Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\users\sachin\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.6-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\sachin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp312-cp312-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.7 MB 8.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/10.7 MB 7.5 MB/s eta 0:00:02
   -------------------- ------------------- 5.5/10.7 MB 9.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.7 MB 12.0 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 12.4 MB/s eta 0:00:00
Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 13.4 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.6 MB 12.3 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 14.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 12.5 MB/s eta 0:00:00
Downloading tzdata-2026.6-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.4 pandas-3.1.0 tzdata-2026.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
#example of series (pass either list or tuple)
import pandas as pd
List_01=[1,2,3,4,5]
Series=pd.Series(List_01)
Series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
#example of series using dictionary
Data_01={"Key1":1,"Key2":2,"Key3":3}
Data_01
pd.Series(Data_01)

Key1    1
Key2    2
Key3    3
dtype: int64

In [14]:
#creating series using dictinary pandas (new data)
calories = {"Day1": 420, "Day2": 380, "Day3": 390}
calSeries = pd.Series(calories)
calSeries

Day1    420
Day2    380
Day3    390
dtype: int64

In [15]:
#example of dataframe using dictionary (2 columns)
new_dict={'Name':["Rajesh","Sunil","Prakash"],
          'Age':[20,30,40]}
df=pd.DataFrame(new_dict)
df

      Name  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [16]:
#example of dataframe using dictionary (3 Columns)
new_dict={'Name':["Rajesh","Sunil","Prakash"],
          'Age':[20,30,40],
          'Education':["BBA","MCA","BTech"]}
df=pd.DataFrame(new_dict)
df

      Name  Age Education
0   Rajesh   20       BBA
1    Sunil   30       MCA
2  Prakash   40     BTech

In [17]:
#example of dataframe using list (2 Columns)
new_list=[["Rajesh",20],
          ["Sunil",30],
          ["Prakash",40]]
df=pd.DataFrame(new_list,columns=["Name","Age"])
df

      Name  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [18]:
#example of dataframe using list (3 Columns)
new_list=[["Rajesh",20,"BBA"],
          ["Sunil",30,"MCA"],
          ["Prakash",40,"BTech"]]
df=pd.DataFrame(new_list,columns=["Name","Age","Education"])
df

      Name  Age Education
0   Rajesh   20       BBA
1    Sunil   30       MCA
2  Prakash   40     BTech

In [19]:
#creating dataframe from dictionary of list and array
newDict = { 'Name': ['Alice', 'Bob', 'Charlie', 'David'], 
            'Age':  [25, 30, 22, 35]}
df=pd.DataFrame(newDict)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   35

In [20]:
#reading csv file into a dataframe
file_path="D:/Python/Data/Small Airline.csv"
df=pd.read_csv(file_path)
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [21]:
#reading excel file into a dataframe
file_path="D:/Python/Data/file.xlsx"
df=pd.read_excel(file_path)
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [ ]:
#installing openpyxl
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [22]:
#saving data to a csv file
df.to_csv("D:/Python/Data/Small Airline.csv", index=False)
print("File saved successfully")

File saved successfully

In [23]:
#saving data to a excel file
df.to_excel("D:/Python/Data/file.xlsx", index=False)
print("File saved successfully")

File saved successfully

In [24]:
#showing dataframe details
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First_name       17 non-null     str
 1   Last_name        17 non-null     str
 2   Age              15 non-null     float64
 3   City             15 non-null     str
 4   Airline          15 non-null     str
 5   Date_of_Journey  17 non-null     datetime64[us]
 6   Dep_Time         17 non-null     str
 7   Arrival_Time     17 non-null     str
 8   Dept_Hour        17 non-null     int64
 9   Dept_Minute      17 non-null     int64
 10  Arrival_Hour     17 non-null     int64
 11  Arrival_Minute   17 non-null     int64
 12  Full Name        17 non-null     str
dtypes: datetime64[us](1), float64(1), int64(4), str(7)
memory usage: 1.9 KB

In [25]:
#showing summary statistics
df.describe()

,Age,Date_of_Journey,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute
count,15.000000,17,17.000000,17.000000,17.000000,17.000000
mean,42.933333,2019-04-07 22:35:17.647058,10.529412,29.411765,12.058824,18.529412
min,36.000000,2019-03-01 00:00:00,5.000000,5.000000,1.000000,0.000000
25%,40.000000,2019-03-12 00:00:00,5.000000,20.000000,8.000000,10.000000
50%,42.000000,2019-03-24 00:00:00,9.000000,25.000000,10.000000,15.000000
75%,46.000000,2019-05-12 00:00:00,11.000000,50.000000,19.000000,25.000000
max,52.000000,2019-06-09 00:00:00,22.000000,55.000000,23.000000,55.000000
std,4.757951,NaN,5.724046,19.193289,6.859943,14.004989

In [ ]:
#showing columns names
df.columns

Index(['First_name', 'Last_name', 'Age', 'City', 'Airline', 'Date_of_Journey',
       'Dep_Time', 'Arrival_Time', 'Dept_Hour', 'Dept_Minute', 'Arrival_Hour',
       'Arrival_Minute', 'Full Name'],
      dtype='str')

In [ ]:
#counting unique values from all the columns
df.value_counts()

First_name  Last_name  Age   City       Airline            Date_of_Journey  Dep_Time  Arrival_Time  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute  Full Name
Amol        Mahul      40.0  LUCKNOW    Jet Airways        2019-03-01       05:05:00  08:00:00      5          5            8             0               Amol-Mahul        2
Praveen     Gurjar     47.0  BANGALURU  Jet Airways        2019-03-12       08:55:00  10:25:00      8          55           10            25              Praveen-Gurjar    2
Sunita      Patil      40.0  CHENNAI    Multiple carriers  2019-05-27       11:25:00  19:15:00      11         25           19            15              Sunita-Patil      2
Ram         Kumar      42.0  BANGALURU  IndiGo             2019-03-24       22:20:00  01:10:00      22         20           1             10              Ram-Kumar         1
Mohan       Sharma     52.0  CHENNAI    Air India          2019-05-01       05:50:00  13:15:00      5          50           13            15              Mohan-Sharma      1
Tina        Ali        36.0  Pune       Jet Airways        2019-06-09       09:25:00  04:25:00      9          25           4             25              Tina-Ali          1
Trishul     Shinde     45.0  Pune       Multiple carriers  2019-05-27       11:25:00  19:15:00      11         25           19            15              Trishul-Shinde    1
Sameer      Patil      39.0  Delhi      Jet Airways        2019-03-12       10:25:00  18:55:00      10         25           18            55              Sameer-Patil      1
Name: count, dtype: int64

In [ ]:
#counting airlines values
df['Airline'].value_counts()

Airline
Jet Airways          8
IndiGo               3
Multiple carriers    3
Air India            1
Name: count, dtype: int64

In [ ]:
#counting cities values
df['City'].value_counts()

City
BANGALURU    4
CHENNAI      4
LUCKNOW      3
Pune         2
Delhi        2
Name: count, dtype: int64

In [ ]:
#showing unique airlines
df['Airline'].unique()

<StringArray>
['IndiGo', 'Air India', 'Jet Airways', nan, 'Multiple carriers']
Length: 5, dtype: str

In [ ]:
#counting unique items
df.nunique()

First_name         12
Last_name          10
Age                 8
City                5
Airline             4
Date_of_Journey     7
Dep_Time            9
Arrival_Time        9
Dept_Hour           8
Dept_Minute         5
Arrival_Hour        9
Arrival_Minute      7
Full Name          12
dtype: int64

In [32]:
#mean of series elements (average value)
list1 = [1,2,3,4,5] 
Series = pd.Series(list1)
Series.mean()

np.float64(3.0)

In [33]:
#median of series elements (middle value)
list1 = [1,2,3,4,5,6] 
Series = pd.Series(list1)
Series.median()

np.float64(3.5)

In [34]:
#mode of series elements (most frequent)
list1 = [1,2,3,4,5,3] 
Series = pd.Series(list1)
Series.mode()

0    3
dtype: int64

In [35]:
#mean of column data (average value)
df['Age'].mean()

np.float64(42.93333333333333)

In [36]:
#median of column data (middle value)
df['Age'].median()

np.float64(42.0)

In [37]:
#mode of column data (most frequent)
df['Airline'].mode()

0    Jet Airways
Name: Airline, dtype: str

In [62]:
#filtering the columns
df[['Airline','Age']]

              Airline   Age
0              IndiGo  42.0
1           Air India  52.0
2         Jet Airways  36.0
3              IndiGo   NaN
4              IndiGo   NaN
5                 NaN  42.0
6                 NaN  52.0
7         Jet Airways  39.0
8         Jet Airways  43.0
9   Multiple carriers  45.0
10        Jet Airways  39.0
11        Jet Airways  40.0
12        Jet Airways  47.0
13  Multiple carriers  40.0
14        Jet Airways  40.0
15        Jet Airways  47.0
16  Multiple carriers  40.0

In [38]:
#filtering the rows (slicing by position)
df[5:8]

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar

In [39]:
#row and column filtering (using loc)
df.loc[4:5,['City','Airline']]      #here it does not ignore the last index

        City Airline
4    LUCKNOW  IndiGo
5  BANGALURU     NaN

In [40]:
#row and column filtering (using iloc)
df.iloc[4:6,3:5]            #here it ignores the last index

        City Airline
4    LUCKNOW  IndiGo
5  BANGALURU     NaN